#ifndef PX_ARM_CPP_PRIMER_CHAPTER_4_CAOY_INCLUDE_CHAPTER6_H_
#define PX_ARM_CPP_PRIMER_CHAPTER_4_CAOY_INCLUDE_CHAPTER6_H_

int Fact(int num);
int Fact();
double Abs();

#endif  // PX_ARM_CPP_PRIMER_CHAPTER_4_CAOY_INCLUDE_CHAPTER6_H_
